config/routes.rb
Rails.application.routes.draw do
  root to: "listings#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :listings
  get 'categories/:category/listings' => "listings#index", as: :listings_by_category
  get 'companies/:company_name/listings' => "listings#index", as: :listings_by_company_name
  get 'industries/:industry/listings' => "listings#index", as: :listings_by_industry
  get 'about' => "pages#about", as: :pages_about
  get 'contact' => "pages#contact", as: :pages_contact
  get 'terms' => "pages#terms", as: :pages_terms
  get 'privacy' => "pages#privacy", as: :pages_privacy
  get "listings/:id/preview" => "listings#preview", as: :preview_job
  # route for payment via razorpay flash
  post '/purchase' => 'orders#purchase_status'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id              :integer          not null, primary key
#  company_email   :string
#  company_name    :string
#  company_website :string
#  expired         :boolean
#  highlight       :boolean
#  industry        :string
#  location        :string
#  logo_displayed  :boolean
#  paid            :boolean
#  sticky          :boolean
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  category_id     :integer
#

class Listing < ApplicationRecord

  belongs_to :category
  has_one :order

  validates_presence_of :title, :description, :category_id, :location, :how_to_apply, :company_name, :company_email, :company_about, :industry
  validates :company_email, format: { with: /\A[^@,\s]+@[^@,\s]+\.[^@,\s]+\z/ }
  validates :company_website, :format => URI::regexp(%w(http https))

  has_rich_text :description
  has_rich_text :how_to_apply
  has_rich_text :company_about

  has_one_attached :company_logo

  def new
    # A listing stays new for 3 days
    self.created_at >= Date.today - 3
  end

  def listing_cost_usd
    price = Price.where(active: true).first
    price.basic
  end

  def total_cost_usd
    tc = listing_cost_usd
    price = Price.where(active: true).first
    if sticky and highlight and logo_displayed
      tc + price.sticky + price.highlight + price.logo_displayed
    elsif sticky and highlight
      tc + price.sticky + price.highlight
    elsif sticky and logo_displayed
      tc + price.sticky + price.logo_displayed
    elsif highlight and logo_displayed
      tc + price.highlight + price.logo_displayed
    elsif sticky
      tc + price.sticky
    elsif logo_displayed
      tc + price.logo_displayed
    elsif highlight
      tc + price.highlight
    else
      tc
    end
  end

  def total_cost_rupees
    total_cost_usd * 72
  end

  def to_param
    slug = title.parameterize
    "#{id}-#{slug}"
  end

  def self.ransackable_associations(auth_object = nil)
    ["category", "company_logo_attachment", "company_logo_blob", "order", "rich_text_company_about", "rich_text_description", "rich_text_how_to_apply"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "company_email", "company_name", "company_website", "created_at", "expired", "highlight", "id", "industry", "location", "logo_displayed", "paid", "sticky", "title", "updated_at"]
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :preview]
  before_action :set_price, only: [:index, :new, :create, :edit, :update, :preview]
  before_action :cant_perform_when_listing_is_paid, only: [:edit, :update, :preview]
  before_action :cant_perform_when_listing_is_unpaid, only: [:show]

  # GET /listings
  # GET /listings.json
  def index
    @categories_for_punchline = Category.all.order(title: :asc)
    @categories = Category.includes(:listings).where('listings.paid' => true).order('listings.created_at DESC', title: :asc)
    @category = Category.find(params[:category]) if params[:category]
    @company_name = params[:company_name]
    @industry = params[:industry]
    puts @industry
    respond_to do |format|
      format.html
      format.json { render :layout => false }
      format.rss { render :layout => false }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @company_name = @listing.company_name
    @other_listings = Listing.where("id != ? and paid = ? and created_at >= ? and company_name = ?", @listing.id, true, Date.today - 60.days, @company_name)
    @other_listings_sticky = @other_listings.where(sticky: true).order('created_at desc')
    @other_listings_non_sticky = @other_listings.where(sticky: false).order('created_at desc')
    # @other_listings_sticky, @other_listings_non_sticky = [], []
    # @other_listings.each do |ol|
    #   @other_listings_sticky << ol if ol.sticky == true
    #   @other_listings_non_sticky << ol if ol.sticky == false
    # end
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to preview_job_path(@listing) }
        format.json { render :preview_job_path, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to preview_job_path(@listing) }
        format.json { render :preview_job_path, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  # def destroy
  #   @listing.destroy
  #   respond_to do |format|
  #     format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  def preview
  end

  def purchase
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_price
      @price = Price.where(active: true).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, :category_id, :location, :how_to_apply, :company_name, :company_logo, :company_website, :company_email, :company_about, :highlight, :sticky, :logo_displayed, :industry)
    end

    def cant_perform_when_listing_is_paid
      if @listing.paid
        flash[:alert] = "No Access"
        redirect_to root_path
      end
    end

    def cant_perform_when_listing_is_unpaid
      if !@listing.paid
        flash[:alert] = "No Access"
        redirect_to root_path
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_apply_panel.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 how_to_apply">
      <h5 style="text-transform:uppercase;font-weight:bold;">Apply for this position</h5>
      <p><%= @listing.how_to_apply %></p>
    </div>
  </div>
</div>

app/views/listings/_display_listing.html.erb
<div class="container">

  <div class="row listing_show">
    <div class="col-lg-10">
      <h2 style="font-weight:700; margin-bottom:0px;"><%= @listing.title %></h2>
      <p style="text-transform:uppercase;font-size:14px;color:#666;">posted <%= @listing.created_at.strftime("%b %d") %></p>
      <p style="font-weight:600; font-size: 22px; margin-bottom:0px;"><%= @listing.company_name %></p>
      <p style="font-weight:700; margin-bottom:18px;">Headquarters: <%= @listing.location %></p>
      <p style="font-weight:700; margin-bottom:18px;">Industry: <span class="industry">  <a href="<%= listings_by_industry_path(@listing.industry) %>" title="View all jobs in <%= @listing.industry %> Industry"><%= @listing.industry %></a></span>&nbsp;&nbsp;<span class="industry"><a href="<%= listings_by_category_path(@listing.category) %>" title="View all <%= @listing.category.title %> jobs"><%= @listing.category.title %></a></span></p>
      <p style="font-weight:700; margin-bottom:0px;"><a href="<%= @listing.company_website %>" target="_blank"><%= @listing.company_website %></a></p>
      <p style="font-weight:700; margin-bottom:0px;"><a href="<%= listings_by_company_name_path(@listing.company_name) %>">View all jobs at <%= @listing.company_name %></a></p>
    </div>
    <div class="col-lg-2">
      <%= image_tag @listing.company_logo.variant(resize: '240x240'), style: "float:right;margin-bottom:36px;", class: 'img-fluid' if @listing.company_logo.attached? %>
      <div class="" style="">
        <%= social_share_button_tag(@listing.title, :url => listing_url(@listing), :image => @listing.company_logo.attached? ? @listing.company_logo.variant(resize: '240x240') : '', desc: @listing.title, via: "dollarjobs108") %>
      </div>
    </div>
  </div>
  <hr>

  <div class="row">
    <div class="col-lg-12">
      <p><%= @listing.description %></p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <h5 style="font-weight:bold;margin-top:18px;">About <%= @listing.company_name %></h5>
      <p><%= @listing.company_about %></p>
    </div>
  </div>

</div>

app/views/listings/_listing.html.erb
<!-- Job Ad Listing Highlighted / Normal -->
<p class="listing" style="<%= 'background:#FFFFE0;' if listing.highlight %>">
  <!-- New Job Ad Listing; Less than 3 days old -->
  <% if listing.new and params[:action] != 'preview' %>
    <span class="new">new</span>
  <% end %>
  <!-- Job Ad Listing has Logo Displayed or Not -->
  <% if listing.company_logo.attached? and listing.logo_displayed %>
    <span style="margin:<%= listing.new and params[:action] != 'preview' ? '0 0px 0 -42px' : '0' %>;">
      <%= image_tag listing.company_logo.variant(resize: '45x45') %>
    </span>
  <% else %>
    <span style="margin:
    <% if listing.new and params[:action] != 'preview' %>
      <%= '0 0px 0 9px' %>
    <% else %>
      <%= '0 51px 0 0px' %>
    <% end %>
    ;"></span>
  <% end %>
  <!-- Job Ad Listing Owner; Company Name -->
  <span class="company_name">
    <strong><%= listing.company_name %></strong>
  </span>
  <!-- Job Ad Listing Title -->
  <span class="title">
    <% unless params[:action] == 'preview' -%>
      <%= link_to truncate(listing.title, :length => 63, :separator => ' '), listing %>
    <% else %>
      <span style="color:#007bff;text-decoration:underline;"><%= truncate(listing.title, :length => 63, :separator => ' ') %></span>
    <% end %>
  </span>
  <!-- Job Ad Listing Location -->
  <span class="location">
    &nbsp;-&nbsp;
    <%= listing.location %>
  </span>
  <!-- Job Ad Listing Location -->
  &nbsp;&nbsp;
  <span class="industry">
    <a href="<%= listings_by_industry_path(listing.industry) %>" title="View all jobs in <%= listing.industry %> Industry"><%= listing.industry %></a>
  </span>
  <% if url_for(:only_path => false).include?('industries') or url_for(:only_path => false).include?('companies') or params[:action] == 'show' -%>
    <!-- Job Ad Listing Category -->
    &nbsp;&nbsp;
    <span class="industry">
      <a href="<%= listings_by_category_path(listing.category) %>" title="View all <%= listing.category.title %> jobs"><%= listing.category.title %></a>
    </span>
  <% end %>
  <!-- Featured Job Ad Listing; Sticky -->
  <span class="sticky" style="<%= "margin-top:9px;" if listing.logo_displayed and params[:action] != 'preview' %>">
    <% if listing.sticky %>
      <em>featured</em>
    <% else %>
      <%= listing.created_at.strftime("%b %d") %>
    <% end %>
  </span>
</p>

app/views/listings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <!-- <h1>Editing Listing</h1> -->
      <%= render 'form', listing: @listing %>
      <!-- <%#= link_to 'Show', @listing %> | -->
      <%#= link_to 'Back', listings_path %>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-lg-7">
      <h1 id="logo">
        <a href="<%= root_path %>"><img src="<%= image_path('logos/logo.png') %>" alt="$$$ Dollar Jobs" class="responsive"></a>
      </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h2 style="text-align:justify;" class="punchline">
        World's magical beast of
        <% @categories_for_punchline.each do |category| -%>
          <% if category.equal? @categories_for_punchline.last %>
            <a href="<%= listings_by_category_path(category) %>">
              <%= category.title %>
            </a>
          <% else -%>
            <a href="<%= listings_by_category_path(category) %>"><%= category.title %></a>,
          <% end %>
        <% end %>
        etc job board with thousands of unique users and hundreds of new positions posted each month!
      </h2>
      <p id="punch_header"><strong>It is 2019 and businesses (including startups) are still struggling to hire good sales and marketing talent.</strong> IF you are seeking desired talent on Indeed, Monster, Careerbuilder, Timesjobs, Naukri etc for your business AND still struggling to find any THEN you have come to the right place <span><a href="<%= root_path %>">dollar jobs</a></span>. <span style="color:#666;text-decoration:underline;"><em>You may wonder, why dollarjobs? <strong>Ans:</strong> Only Sales and Marketing efforts bring dollars (money) into your business, nothing else</em></span>.</p>
      <center>
        <%= link_to(raw("Post a job ad: <em><span style='text-decoration:line-through;font-size:90%;'>$249 for 60 days</span></em>"), new_listing_path, class: "btn btn-success", style: "margin-bottom:36px;", alt: "Post a sales job ad for $#{@price.basic} for 60 days") %>
        <br>
        <span style='font-weight:bold;color:#c00;position:relative;top:-36px;'>
          &nbsp;&nbsp;$<%= @price.basic %> for 60 days
          <em style="font-size:12px;color:#333;">(Limited Time Offer)</em>
         </span>
      </center>
    </div>
  </div>
</div>

<hr>

<div class="container-fluid">
  <div class="row">
    <!-- Begin Mailchimp Signup Form -->
    <link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
    <style type="text/css">
      #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
      /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
         We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
    </style>
    <div id="mc_embed_signup">
    <form action="https://gmail.us20.list-manage.com/subscribe/post?u=db053d29d2bcb15cacae4d12c&amp;id=acb74f7ee0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <div id="mc_embed_signup_scroll">
      <label for="mce-EMAIL">Get new job listing ads sent to your email inbox every week</label>
      <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_db053d29d2bcb15cacae4d12c_acb74f7ee0" tabindex="-1" value=""></div>
        <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
        </div>
    </form>
    </div>
    <!--End mc_embed_signup-->
  </div>
</div>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-lg-12 listings">
      <!-- Display all listing for single category -->
      <% if @category -%>
        <%= content_for :rss_feed, auto_discovery_link_tag(:rss, listings_by_category_url(format: :rss)) %>
        <h4 class="listing-anchor">
          <%= link_to @category.title + ' Jobs', listings_by_category_path(@category) %>
          <%= link_to image_tag('rss-feed.svg', style: "margin-top:-9px;"), listings_by_category_url(:format => :rss) %>
        </h4>
        <% @category.listings.where("paid = ? and created_at >= ?", true, Date.today - 60.days).order(created_at: :desc).sort_by{ |l| l.sticky ? 0 : 1 }.each do |listing| -%>
          <%= render 'listing', listing: listing %>
        <% end %>
        <p class="back_and_other_links">
          <span> <%= link_to "← Back to all jobs", listings_path %> </span>
        </p>
      <!-- Display listings for a company -->
      <% elsif @company_name -%>
        <% unless Listing.where("paid = ? and created_at >= ? and company_name = ?", true, Date.today - 60.days, @company_name).empty? -%>
          <%= content_for :rss_feed, auto_discovery_link_tag(:rss, listings_by_company_name_url(format: :rss)) %>
          <h4 class="listing-anchor">
            <%= link_to 'Jobs at ' +  @company_name, listings_by_company_name_path(@company_name) %>
            <%= link_to image_tag('rss-feed.svg', style: "margin-top:-9px;"), listings_by_company_name_url(format: :rss) %>
          </h4>
          <% Listing.where("paid = ? and created_at >= ? and company_name = ?", true, Date.today - 60.days, @company_name).order(created_at: :desc).sort_by{ |l| l.sticky ? 0 : 1 }.each do |listing| -%>
            <%= render 'listing', listing: listing %>
          <% end %>
        <% else %>
          <div class="" style="background:#ccc;padding:36px;margin-top:36px;">
            <span>Sorry, the company you were looking for doesn’t seem to exist anymore.</span>
          </div>
        <% end %>
        <p class="back_and_other_links">
          <span> <%= link_to "← Back to all jobs", listings_path %> </span>
        </p>
      <!-- Display listings for a industry -->
      <% elsif @industry -%>
        <% unless Listing.where("paid = ? and created_at >= ? and industry = ?", true, Date.today - 60.days, @industry).empty? -%>
          <%= content_for :rss_feed, auto_discovery_link_tag(:rss, listings_by_industry_url(format: :rss)) %>
          <h4 class="listing-anchor">
            <%= link_to @industry + ' Industry Jobs', listings_by_industry_path(@industry) %>
            <%= link_to image_tag('rss-feed.svg', style: "margin-top:-9px;"), listings_by_industry_url(format: :rss) %>
          </h4>
          <% Listing.where("paid = ? and created_at >= ? and industry = ?", true, Date.today - 60.days, @industry).order(created_at: :desc).sort_by{ |l| l.sticky ? 0 : 1 }.each do |listing| -%>
            <%= render 'listing', listing: listing %>
          <% end %>
        <% else %>
          <div class="" style="background:#ccc;padding:36px;margin-top:36px;">
            <span>Sorry, the industry you were looking for doesn’t seem to have any job listing ads anymore.</span>
          </div>
        <% end %>
        <p class="back_and_other_links">
          <span> <%= link_to "← Back to all jobs", listings_path %> </span>
        </p>
      <!-- Display all listings -->
      <% else -%>
        <%= content_for :rss_feed, auto_discovery_link_tag(:rss, listings_url(format: :rss)) %>
        <% @categories.each do |category| %>
          <h4 class="listing-anchor">
            <%= link_to category.title + ' Jobs', listings_by_category_path(category) %>
            <%= link_to image_tag('rss-feed.svg', style: "margin-top:-9px;"), listings_by_category_url(category: category, :format => :rss) %>
          </h4>

          <% if category.listings.where("created_at >= ?", Date.today - 60.days).size > 30 %>
            <% category.listings.where("paid = ? and created_at >= ?", true, Date.today - 60.days).order(created_at: :desc).limit(30).sort_by{ |l| l.sticky ? 0 : 1 }.each do |listing| -%>
              <%= render 'listing', listing: listing %>
            <% end %>
            <p class="back_and_other_links">
              <span> <%= link_to "View all " + category.title + " jobs →", listings_by_category_path(category) %> </span>
            </p>
          <% else %>
            <% category.listings.where("paid = ? and created_at >= ?", true, Date.today - 60.days).order(created_at: :desc).sort_by{ |l| l.sticky ? 0 : 1 }.each do |listing| -%>
              <%= render 'listing', listing: listing %>
            <% end %>
          <% end %>

        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <!-- <h1>New Listing</h1> -->
      <%= render 'form', listing: @listing %>
      <%#= link_to 'Back', listings_path %>
    </div>
  </div>
</div>

app/views/listings/preview.html.erb
<div class="container">

  <div class="row">
    <div class="col-lg-12" style="margin-bottom:18px;">
      <h3>
        <a href="<%= root_path %>">
          <img src="<%= image_path('logos/logo-small.png') %>" alt="$$$ Dollar Jobs" width="180">
        </a>
      </h3>
      <ul style="float:right; margin:0 20px; padding: 0;margin-top:-39px;">
        <li style="list-style-type: none; display: inline; background-color: #eee; color: #111; border: 0;padding: 12px;">1. Create your ad</li>
        <li style="list-style-type: none; display: inline; background-color: #2192f1; color: #fff; font-weight: bold; text-shadow: 0 1px 0 #1963a2; border: 0;padding: 12px;">2. Preview</li>
        <li style="list-style-type: none; display: inline; background-color: #eee; color: #111; border: 0;padding: 12px;">3. Purchase</li>
      </ul>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <strong style="font-weight: bold; font-size:20px;color:#c00;"><u>STEP 2 (OF 3): PREVIEW YOUR AD</u></strong>
      <br><br>
    </div>
  </div>

</div>

<%= render 'display_listing' %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render 'apply_panel' %>
    </div>
  </div>
  <hr>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12 listings">
      <h6 style="color:#c00;">Preview of your ad as it will be displayed on the Homepage</h6>
      <%= render 'listing', listing: @listing %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row" style="margin-top:36px;">
    <div class="actions col-lg-6">
      <%= render 'orders/razorpay' %> or <u><%= link_to "Make changes", edit_listing_path(@listing) %></u>
    </div>
    <div class="col-lg-6">
      <h4 style="color:#c00;float:right;">Your total cost is:
        $<span id="order_total"><%= @listing.total_cost_usd ? @listing.total_cost_usd : @listing.listing_cost_usd %></span>
      </h4>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row" style="background:#000;color:#aaa;margin-top:45px;margin-bottom:-45px;padding-bottom:18px;border-bottom:1px solid #333;">
    <div class="col-lg-12">
      <center>
        <a href="https://www.razorpay.com" target="_blank" alt="Alternate to Stripe for India" title="Alternate to Stripe for India"><%= image_tag 'powered-by-razorpay.png', alt: 'All payments powered by Razorpay - PCI Compliant', width: 210, style: 'margin-top:36px;' %></a>
        <p style="font-size:10px;">All payments are processed in INR (Indian Rupees). <br> If you are outside of India then you can select <em>'Card'</em> option to pay. <br> USD is converted to INR at an exchange rate of Rs 72 for this quarter (Updated quarterly).</p>
      </center>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<%= content_for(:title, "#{ @listing.title } at #{ @listing.company_name } in #{ @listing.location }") %>

<div class="container">

  <div class="row">
    <div class="col-lg-12" style="margin-bottom:18px;">
      <h3>
        <a href="<%= root_path %>">
          <img src="<%= image_path('logos/logo-small.png') %>" alt="$$$ Dollar Jobs" width="180">
        </a>
      </h3>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-lg-12">
      <p class="back_and_other_links_show">
        <span><%= link_to "← Back to all jobs", listings_path %></span>
        <span style="float:right;"><%= link_to "See more #{@listing.category.title} jobs →", listings_by_category_path(@listing.category) %></span>
      </p>
      <br>
    </div>
  </div>
</div>

<%= render 'display_listing' %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render 'apply_panel' %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-lg-12 listings">
      <!-- Display other listings for a company -->
      <% unless @other_listings.empty? -%>
        <center><h2 style="margin:90px 0 36px 0;font-weight:bold;">Other job ad listings at <%= @company_name %></h2></center>
        <%= content_for :rss_feed, auto_discovery_link_tag(:rss, listings_by_company_name_url(@company_name, format: :rss)) %>
        <% @other_listings_sticky.each do |listing| -%>
          <%= render 'listing', listing: listing %>
        <% end %>
        <% @other_listings_non_sticky.each do |listing| -%>
          <%= render 'listing', listing: listing %>
        <% end %>
        <p class="back_and_other_links">
          <span> <%= link_to "← Back to all jobs", listings_path %> </span>
          <span style="float:right;"><%= link_to "See more #{@listing.category.title} jobs →", listings_by_category_path(@listing.category) %></span>
        </p>
        <center>
          <%= link_to "View all jobs at #{@company_name}", listings_by_company_name_path(@company_name), class: "btn btn-primary", style: "margin-top:36px;" %>
        </center>
      <% end %>
    </div>
  </div>
</div>