config/routes.rb
Rails.application.routes.draw do
  root to: "listings#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :listings
  get 'categories/:category/listings' => "listings#index", as: :listings_by_category
  get 'companies/:company_name/listings' => "listings#index", as: :listings_by_company_name
  get 'industries/:industry/listings' => "listings#index", as: :listings_by_industry
  get 'about' => "pages#about", as: :pages_about
  get 'contact' => "pages#contact", as: :pages_contact
  get 'terms' => "pages#terms", as: :pages_terms
  get 'privacy' => "pages#privacy", as: :pages_privacy
  get "listings/:id/preview" => "listings#preview", as: :preview_job
  # route for payment via razorpay flash
  post '/purchase' => 'orders#purchase_status'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_notices.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice]%>
  </div>
<% elsif flash[:error]%>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error]%>
  </div>
 <% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/layouts/_free_book.html.erb
<section class="free_book_section">
  <div class="container-fluid">
    <div class="row free-book">
      <div class="col-lg-1"></div>
      <div class="col-lg-3">
        <img src="<%= image_path('ebook-cover-6keyskills-web.jpg') %>" alt="6 Key Skills you MUST possess to become Top Salesman - FREE ebook" style="display:block;width:300px;height:auto;" align="top">
      </div>
      <div class="col-lg-1"></div>
      <div class="col-lg-6">
        <center>
          <h4 style="">Becoming a Salesman is NOT easy, it is like joining military.</h4>
          <h2>And, becoming a Top Salesman is Super Tough.</h2>
          <p>We have written a FREE ebook - <strong>6 Key Skills you Must Possess to Become a Top Salesperson</strong> - to help you achieve your mission of becoming a Top Salesman or Top Saleswoman and of generating a sustainable 6-figure income for now and for tomorrow.</p>
          <div class="" style="border:1px solid #666;padding:18px;margin-top:36px;">
            <!-- Begin Mailchimp Signup Form -->
            <link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
            <style type="text/css">
              #mc_embed_signup_dark{background:#000; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
              /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
                 We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
            </style>
            <div id="mc_embed_signup_dark">
            <form action="https://gmail.us20.list-manage.com/subscribe/post?u=db053d29d2bcb15cacae4d12c&amp;id=acb74f7ee0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
              <div id="mc_embed_signup_scroll">
                <label for="mce-EMAIL">Receive a FREE copy of this eBook in your inbox</label>
                <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
                <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_db053d29d2bcb15cacae4d12c_acb74f7ee0" tabindex="-1" value=""></div> <br><br>
                <div class="clear"><input type="submit" value="Send me my FREE copy now >>>" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary"></div>
              </div>
            </form>
            </div>
            <!--End mc_embed_signup-->
          </div>
        </center>
      </div>
      <div class="col-lg-1"></div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dollar Jobs - <%= content_for?(:title) ? yield(:title) : 'The Biggest Sales Jobs Board on Planet' %></title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="author" content="DollarJobs | Mittaltiger Enterprises">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'DollarJobs is the Biggest Sales Jobs Board and Portal on Planet. Post and Apply for all kind of sales, business development, marketing, digital marketing, advertising etc jobs.' %>">
    <meta name="keywords" content="Dollarjobs, Dollar, Jobs, Global, Planet, United States, Asia, Middle East, Africa, Europe, Russia, Oceania, Pacific, Australia, India, South America, Sales, Business Development, Marketing, Digital Marketing, Advertising, Communication, Selling, Sell, Naukri, Bechna, Success, Money, Goals, Achieve, Targets">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- favicon -->
    <%= favicon_link_tag asset_path('favicons/favicon.ico') %>
    <!-- Apple touch icons -->
    <link href="<%= asset_path('favicons/apple-icon-57x57.png') %>" rel="apple-touch-icon" sizes="57x57" />
    <link href="<%= asset_path('favicons/apple-icon-60x60.png') %>" rel="apple-touch-icon" sizes="60x60" />
    <link href="<%= asset_path('favicons/apple-icon-72x72.png') %>" rel="apple-touch-icon" sizes="72x72" />
    <link href="<%= asset_path('favicons/apple-icon-76x76.png') %>" rel="apple-touch-icon" sizes="76x76" />
    <link href="<%= asset_path('favicons/apple-icon-114x114.png') %>" rel="apple-touch-icon" sizes="114x114" />
    <link href="<%= asset_path('favicons/apple-icon-120x120.png') %>" rel="apple-touch-icon" sizes="120x120" />
    <link href="<%= asset_path('favicons/apple-icon-144x144.png') %>" rel="apple-touch-icon" sizes="144x144" />
    <link href="<%= asset_path('favicons/apple-icon-152x152.png') %>" rel="apple-touch-icon" sizes="152x152" />
    <link href="<%= asset_path('favicons/apple-icon-180x180.png') %>" rel="apple-touch-icon" sizes="180x180" />
    <!-- Android touch icons -->
    <link href="<%= asset_path('favicons/android-icon-192x192.png') %>" rel="icon" sizes="192x192" />
    <!-- Windows touch icons -->
    <meta name="msapplication-square70x70logo" content="<%= asset_path('favicons/ms-icon-70x70.png') %>">
    <meta name="msapplication-square144x144logo" content="<%= asset_path('favicons/ms-icon-144x144.png') %>">
    <meta name="msapplication-square150x150logo" content="<%= asset_path('favicons/ms-icon-150x150.png') %>">
    <meta name="msapplication-square310x310logo" content="<%= asset_path('favicons/ms-icon-310x310.png') %>">
    <!-- Windows tile theme color -->
    <meta name="msapplication-TileColor" content="#fff">

    <!-- META TAGS -->
    <link rel="canonical" href="<%= url_for(:only_path => false) %>" />

    <% if params[:controller] == 'listings' and params[:action] == 'show' %>
    <link rel="image_src" href="<%= @listing.company_logo.attached? ? asset_path(url_for(@listing.company_logo)) : '' %>">
    <meta property="og:image" content="<%= @listing.company_logo.attached? ? asset_path(url_for(@listing.company_logo)) : '' %>">
    <meta name="twitter:image" content="<%= @listing.company_logo.attached? ? asset_path(url_for(@listing.company_logo)) : '' %>">
    <% else %>
    <link rel="image_src" href="<%= asset_path('logos/logo.png') %>">
    <meta property="og:image" content="<%= asset_path('logos/logo.png') %>">
    <meta name="twitter:image" content="<%= asset_path('logos/logo.png') %>">
    <% end %>

    <meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : 'DollarJobs is the Biggest Sales Jobs Board and Portal on Planet. Post and Apply for all kind of sales, business development, marketing, digital marketing, advertising etc jobs.' %>">

    <meta property="og:email" content="support@dollarjobs.co" />

    <meta property="og:site_name" content="DollarJobs" />
    <meta property="og:title" content="DollarJobs <%= content_for?(:title) ? ' - ' + yield(:title) : ' - The Biggest Sales Jobs Board on Planet' %>">
    <meta property="og:type" content="article">
    <meta property="og:url" content="<%= url_for(:only_path => false) %>">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@dollarjobs108">
    <meta name="twitter:url" content="<%= url_for(:only_path => false) %>">
    <meta name="twitter:title" content="DollarJobs <%= content_for?(:title) ? ' - ' + yield(:title) : ' - The Biggest Sales Jobs Board on Planet' %>">
    <meta name="twitter:description" content="<%= content_for?(:description) ? yield(:description) : 'DollarJobs is the Biggest Sales Jobs Board and Portal on Planet. Post and Apply for all kind of sales, business development, marketing, digital marketing, advertising etc jobs.' %>">
    <meta name="twitter:creator" content="@dollarjobs108">
    <!-- META TAGS ENDS -->

    <% if Rails.env == "production" %>
      <!-- Google site verification -->
      <meta name="google-site-verification" content="Hpg3YxUIJoI1UrcNtRwRsa8FfLEs71b7fvO0tsmP80E" />

      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-138035813-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-138035813-1');
      </script>
    <% end %>

    <%= yield :rss_feed %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash_notices' %>
    <div id="main">
      <%= yield %>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="footer col-lg-12">
          <center>
            <p>
              &copy; 2019 Dollar Jobs - A product of Mittaltiger Advertising. <br>
              <span style="font-size:12px;color:#999;">
              Mittaltiger Advertising is a division of <a href="https://www.mittaltiger.com/about/divisions/" target="_blank">Mittaltiger Enterprises</a>.
              </span>
            </p>
            <ul class="footer_menu">
              <li> • <a href="<%= pages_about_path %>">About</a></li>
              <li> • <a href="/blog">Blog</a></li>
              <li> • <a href="<%= pages_terms_path %>">Terms</a></li>
              <li> • <a href="<%= pages_privacy_path %>">Privacy</a></li>
              <li> • <a href="<%= pages_contact_path %>">Contact</a></li>
            </ul>
            <p style="display:block;" class="post_a_job">
              <a href="<%= new_listing_path %>">Post a job ad - <span style="text-decoration:line-through;">$249</span> $<%= Price.where(active: true).first.basic %> for 60 days</a>
            </p>
            <p class="social_icons">
              <!-- Add font awesome icons -->
              <a href="https://www.facebook.com/Dollar-Jobs-526296364443536" target="_blank" class="fa fa-facebook" style="font-size:24px;"></a>
              <a href="https://twitter.com/dollarjobs108" target="_blank" class="fa fa-twitter" style="font-size:24px;"></a>
            </p>
          </center>
       </div>
      </div>
    </div>
    <% if (params[:controller] == 'listings' and (params[:action] == 'index' or params[:action] == 'show')) or
          (params[:controller] == 'pages' and (params[:action] == 'about' or params[:action] == 'contact'))
    -%>
      <%= render 'layouts/free_book' %>
    <% end %>
  </body>
</html>